### ISSUE TITLE
Kubernetes Resource action: patch is not supported

### ISSUE THREAD

**Issue by shanesiebken** [argoproj/argo#1223]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report
**What happened**:
Patch failed with error: required flag "patch" not set.
**What you expected to happen**:
Patch file to be executed successfully
**How to reproduce it (as minimally and precisely as possible)**:
Create a workflow with template of type kubernetes resource with action = patch
**Anything else we need to know?**:
In `argo/workflow/executor/resource.go`, the command is always set with a flag `-f` pointing to the manifest. For most kubectl commands, this works, but a patch requires the patch manifest to be pointed at with the flag `-p` instead. This should be conditionalized, or the documentation for kubernetes resource templates should be updated to explain `patch` is not supported.
**Environment**:
- Argo version:
v2.2.1
- Kubernetes version :
1.13

**Other debugging information (if applicable)**:
- workflow result:
```
STEP                PODNAME                    DURATION  MESSAGE
 ✖ <workflow_step>                                       child <workflow_child> failed
 ├---○ build                                             when 'false == "true"' evaluated false
 └---✖ deploy      <workflow_step>                 2s        Error: required flag(s) "patch" not set


Examples:
  # Partially update a node using a strategic merge patch. Specify the patch as JSON.
  kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
  
  # Partially update a node using a strategic merge patch. Specify the patch as YAML.
  kubectl patch node k8s-node-1 -p $'spec:\n unschedulable: true'
  
  # Partially update a node identified by the type and name specified in "node.json" using strategic merge patch.
  kubectl patch -f node.json -p '{"spec":{"unschedulable":true}}'
  
  # Update a container's image; spec.containers[*].name is required because it's a merge key.
  kubectl patch pod valid-pod -p '{"spec":{"containers":[{"name":"kubernetes-serve-hostname","image":"new image"}]}}'
  
  # Update a container's image using a json patch with positional arrays.
  kubectl patch pod valid-pod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/image", "value":"new image"}]'

Options:
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats.
      --dry-run=false: If true, only print the object that would be sent, without sending it.
  -f, --filename=[]: Filename, directory, or URL to files identifying the resource to update
      --local=false: If true, patch will operate on the content of the file, not the server-side resource.
  -o, --output='': Output format. One of: json|yaml|name|template|go-template|go-template-file|templatefile|jsonpath|jsonpath-file.
  -p, --patch='': The patch to be applied to the resource JSON file.
      --record=false: Record current kubectl command in the resource annotation. If set to false, do not record the command. If set to true, record the command. If not set, default to updating the existing annotation value only if one already exists.
  -R, --recursive=false: Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests organized within the same directory.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --type='strategic': The type of patch being provided; one of [json merge strategic]

Usage:
  kubectl patch (-f FILENAME | TYPE NAME) -p PATCH [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

required flag(s) "patch" not set
```
- executor logs:
```
time="2019-02-16T18:12:21Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2019-02-16T18:12:21Z" level=info msg="kubectl patch -f /tmp/manifest.yaml -o name"
time="2019-02-16T18:12:21Z" level=fatal msg="Error: required flag(s) \"patch\" not set...
```
- workflow-controller logs:
Not applicable

**Comment by sarabala1979** [comment]
This issue has been fixed and merged into master.

PR: #1245

**Comment by ian-howell** [comment]
It seems as though this issue is not yet resolved. Currently, the patch will fail with the following message:

```
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json
```

This can be resolved by adding the `--type merge` flag to the patch command. I'm working on a PR
