### ISSUE TITLE
CronWorkflows started twice on every schedule

### ISSUE THREAD

**Issue by vilmosnagy** [argoproj/argo#2773]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I've created the sample CronWorkflow from the [docs](https://github.com/argoproj/argo/blob/master/docs/cron-workflows.md), but Argo starts them twice on every tick.

```
[vilmosnagy@vnagy-dell graph]$ argo cron create /tmp/example.yaml 
Name:                          test-cron-wf
Namespace:                     default
Created:                       Tue Apr 21 13:16:18 +0200 (now)
Schedule:                      * * * * *
Suspended:                     false
StartingDeadlineSeconds:       0
ConcurrencyPolicy:             Replace
[vilmosnagy@vnagy-dell graph]$ argo list
NAME                             STATUS      AGE   DURATION   PRIORITY
test-cron-wf-g6rdh               Running     21s   21s        0
test-cron-wf-jzn5g               Running     22s   21s        0
test-cron-wf-dn6j8               Running     1m    1m         0
test-cron-wf-28skf               Running     1m    1m         0
test-cron-wf-mz7vf               Error       2m    1m         0

```

You can see that the `test-cron-wf` was started twice in the same minute when it should start only once. It happens with every CronWorkflow in this k8s cluster.

**What you expected to happen**:

The CronWorkflow should start once in every minute.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create the test workflow from the [docs](https://github.com/argoproj/argo/blob/master/docs/cron-workflows.md)
1. Wait the next minute

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.6.1
  BuildDate: 2020-03-04T21:25:34Z
  GitCommit: 842739d7831cc5b417c4f524ed85288408a32bbf
  GitTreeState: clean
  GitTag: v2.6.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-03-25T14:58:59Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.13.8
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-06-19T16:32:14Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
[vilmosnagy@vnagy-dell graph]$ kubectl logs -n argo-system $(kubectl get pods -l app=argo-workflow-controller -n argo-system -o name) --since=2m
time="2020-04-21T11:32:32Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-74924,Name:test-cron-wf-74924,DisplayName:test-cron-wf-74924,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-21 11:31:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Running -> Error"
time="2020-04-21T11:32:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-74924,Name:test-cron-wf-74924,DisplayName:test-cron-wf-74924,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Error,BoundaryID:,Message:,StartedAt:2020-04-21 11:31:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: failed to save outputs: Failed to establish pod watch: unknown (get pods)"
time="2020-04-21T11:32:32Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Updated message  -> failed to save outputs: Failed to establish pod watch: unknown (get pods)" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Marking workflow completed" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=warning msg="Workflow 'test-cron-wf-74924' from CronWorkflow 'test-cron-wf' completed"
time="2020-04-21T11:32:32Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:32:32Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-74924\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=28093757 workflow=test-cron-wf-74924
time="2020-04-21T11:32:32Z" level=warning msg="Workflow 'default/test-cron-wf-f8th5' no longer exists"
time="2020-04-21T11:32:32Z" level=info msg="Deleted Workflow 'test-cron-wf-f8th5' due to CronWorkflow 'test-cron-wf' history limit"
time="2020-04-21T11:32:32Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-htkjx,Name:test-cron-wf-htkjx,DisplayName:test-cron-wf-htkjx,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-21 11:31:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Running -> Error"
time="2020-04-21T11:32:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-htkjx,Name:test-cron-wf-htkjx,DisplayName:test-cron-wf-htkjx,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Error,BoundaryID:,Message:,StartedAt:2020-04-21 11:31:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: failed to save outputs: Failed to establish pod watch: unknown (get pods)"
time="2020-04-21T11:32:32Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=info msg="Updated message  -> terminated" namespace=default workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=info msg="Marking workflow completed" namespace=default workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=warning msg="Workflow 'test-cron-wf-htkjx' from CronWorkflow 'test-cron-wf' completed"
time="2020-04-21T11:32:32Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=28093763 workflow=test-cron-wf-htkjx
time="2020-04-21T11:32:32Z" level=info msg="Processing default/test-cron-wf"
time="2020-04-21T11:32:32Z" level=info msg="CronWorkflow default/test-cron-wf added"
time="2020-04-21T11:32:32Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:32:32Z" level=info msg="Deleted Workflow 'test-cron-wf-htkjx' due to CronWorkflow 'test-cron-wf' history limit"
time="2020-04-21T11:32:32Z" level=warning msg="Workflow 'default/test-cron-wf-htkjx' no longer exists"
time="2020-04-21T11:32:33Z" level=info msg="Labeled pod default/test-cron-wf-74924 completed"
time="2020-04-21T11:32:59Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:32:59Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:00Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:00Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:00Z" level=info msg="Processing default/test-cron-wf"
time="2020-04-21T11:33:00Z" level=info msg="CronWorkflow default/test-cron-wf added"
time="2020-04-21T11:33:00Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:00Z" level=info msg="Pod node {test-cron-wf-mz7vf test-cron-wf-mz7vf test-cron-wf-mz7vf Pod whalesay nil    Pending   2020-04-21 11:33:00.040568296 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  <nil> nil nil [] []} initialized Pending" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:00Z" level=info msg="Created pod: test-cron-wf-mz7vf (test-cron-wf-mz7vf)" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093825 workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:00Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:00Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:01Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:01Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-mz7vf,Name:test-cron-wf-mz7vf,DisplayName:test-cron-wf-mz7vf,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:,StartedAt:2020-04-21 11:33:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: ContainerCreating"
time="2020-04-21T11:33:01Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:01Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093831 workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:02Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:02Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:02Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-mz7vf,Name:test-cron-wf-mz7vf,DisplayName:test-cron-wf-mz7vf,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:ContainerCreating,StartedAt:2020-04-21 11:33:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Pending -> Running"
time="2020-04-21T11:33:02Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-mz7vf\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:02Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:02Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:02Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093839 workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:03Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:32Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-z7255,Name:test-cron-wf-z7255,DisplayName:test-cron-wf-z7255,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-21 11:32:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Running -> Error"
time="2020-04-21T11:33:32Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-z7255,Name:test-cron-wf-z7255,DisplayName:test-cron-wf-z7255,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Error,BoundaryID:,Message:,StartedAt:2020-04-21 11:32:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: failed to save outputs: Failed to establish pod watch: unknown (get pods)"
time="2020-04-21T11:33:32Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Updated message  -> terminated" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Marking workflow completed" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:32Z" level=warning msg="Workflow 'test-cron-wf-z7255' from CronWorkflow 'test-cron-wf' completed"
time="2020-04-21T11:33:32Z" level=info msg="Processing default/test-cron-wf"
time="2020-04-21T11:33:32Z" level=info msg="CronWorkflow default/test-cron-wf added"
time="2020-04-21T11:33:32Z" level=error msg="Unable to update CronWorkflow 'test-cron-wf': failed to update CronWorkflow: Operation cannot be fulfilled on cronworkflows.argoproj.io \"test-cron-wf\": the object has been modified; please apply your changes to the latest version and try again"
time="2020-04-21T11:33:32Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:32Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-z7255\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=28093897 workflow=test-cron-wf-z7255
time="2020-04-21T11:33:32Z" level=warning msg="Workflow 'default/test-cron-wf-74924' no longer exists"
time="2020-04-21T11:33:32Z" level=info msg="Deleted Workflow 'test-cron-wf-74924' due to CronWorkflow 'test-cron-wf' history limit"
time="2020-04-21T11:33:33Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-9zrr6,Name:test-cron-wf-9zrr6,DisplayName:test-cron-wf-9zrr6,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-21 11:32:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Running -> Error"
time="2020-04-21T11:33:33Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-9zrr6,Name:test-cron-wf-9zrr6,DisplayName:test-cron-wf-9zrr6,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Error,BoundaryID:,Message:,StartedAt:2020-04-21 11:32:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: failed to save outputs: Failed to establish pod watch: unknown (get pods)"
time="2020-04-21T11:33:33Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Updated message  -> failed to save outputs: Failed to establish pod watch: unknown (get pods)" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Marking workflow completed" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=warning msg="Workflow 'test-cron-wf-9zrr6' from CronWorkflow 'test-cron-wf' completed"
time="2020-04-21T11:33:33Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-9zrr6\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:33Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=28093908 workflow=test-cron-wf-9zrr6
time="2020-04-21T11:33:33Z" level=warning msg="Workflow 'default/test-cron-wf-z7255' no longer exists"
time="2020-04-21T11:33:33Z" level=error msg="Unable to delete Failed Workflows of CronWorkflow 'test-cron-wf': error deleting workflow 'test-cron-wf-z7255': &{{{%!e(string=) %!e(string=)} {%!e(string=) %!e(string=) %!e(string=) %!e(*int64=<nil>)} %!e(string=Failure) %!e(string=workflows.argoproj.io \"test-cron-wf-z7255\" not found) %!e(v1.StatusReason=NotFound) %!e(*v1.StatusDetails=&{test-cron-wf-z7255 argoproj.io workflows  [] 0}) %!e(int32=404)}}"
time="2020-04-21T11:33:34Z" level=info msg="Labeled pod default/test-cron-wf-9zrr6 completed"
time="2020-04-21T11:33:59Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:33:59Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:33:59Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:33:59Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:33:59Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:00Z" level=info msg="Running test-cron-wf"
time="2020-04-21T11:34:00Z" level=info msg="Execution control for pod test-cron-wf-mz7vf out-of-sync desired: 0001-01-01 00:00:00 +0000 UTC, actual: 0001-01-01 00:00:00 +0000 UTC" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:00Z" level=info msg="Updating execution control of test-cron-wf-mz7vf: {\"deadline\":\"0001-01-01T00:00:00Z\"}" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:00Z" level=info msg="Processing default/test-cron-wf"
time="2020-04-21T11:34:00Z" level=info msg="CronWorkflow default/test-cron-wf added"
time="2020-04-21T11:34:00Z" level=info msg="Pod node {test-cron-wf-28skf test-cron-wf-28skf test-cron-wf-28skf Pod whalesay nil    Pending   2020-04-21 11:34:00.032224852 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  <nil> nil nil [] []} initialized Pending" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="Signalling test-cron-wf-mz7vf of updates" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:00Z" level=info msg="https://10.233.0.1:443/api/v1/namespaces/default/pods/test-cron-wf-mz7vf/exec?command=sh&command=-c&command=kill+-s+USR2+%24%28pidof+argoexec%29&container=wait&stderr=true&stdout=true&tty=false"
time="2020-04-21T11:34:00Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:00Z" level=info msg="Created pod: test-cron-wf-28skf (test-cron-wf-28skf)" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="test-cron-wf has 'ConcurrencyPolicy: Replace' and has active Workflows"
time="2020-04-21T11:34:00Z" level=info msg="stopping 'test-cron-wf-mz7vf'"
time="2020-04-21T11:34:00Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-28skf\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:00Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093976 workflow=test-cron-wf-28skf
time="2020-04-21T11:34:00Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:00Z" level=error msg="failed to update CronWorkflow: Operation cannot be fulfilled on cronworkflows.argoproj.io \"test-cron-wf\": the object has been modified; please apply your changes to the latest version and try again"
time="2020-04-21T11:34:00Z" level=info msg="Pod node {test-cron-wf-dn6j8 test-cron-wf-dn6j8 test-cron-wf-dn6j8 Pod whalesay nil    Pending   2020-04-21 11:34:00.128862354 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  <nil> nil nil [] []} initialized Pending" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=warning msg="Signal command failed: unable to upgrade connection: container not found (\"wait\")" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:00Z" level=info msg="Skipped pod test-cron-wf-dn6j8 (test-cron-wf-dn6j8) creation: already exists" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-dn6j8\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:00Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093982 workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:01Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:01Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:01Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-28skf,Name:test-cron-wf-28skf,DisplayName:test-cron-wf-28skf,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:,StartedAt:2020-04-21 11:34:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: ContainerCreating"
time="2020-04-21T11:34:01Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-28skf\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:01Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:01Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:01Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093986 workflow=test-cron-wf-28skf
time="2020-04-21T11:34:01Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:01Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-dn6j8,Name:test-cron-wf-dn6j8,DisplayName:test-cron-wf-dn6j8,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:,StartedAt:2020-04-21 11:34:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} message: ContainerCreating"
time="2020-04-21T11:34:01Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:01Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-dn6j8\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:01Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:01Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:01Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28093990 workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:02Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:02Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:02Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-dn6j8
time="2020-04-21T11:34:02Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:02Z" level=info msg="Updating node &NodeStatus{ID:test-cron-wf-28skf,Name:test-cron-wf-28skf,DisplayName:test-cron-wf-28skf,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Pending,BoundaryID:,Message:ContainerCreating,StartedAt:2020-04-21 11:34:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,} status Pending -> Running"
time="2020-04-21T11:34:02Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-28skf\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:02Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:02Z" level=info msg="Enforcing history limit for 'test-cron-wf'"
time="2020-04-21T11:34:02Z" level=info msg="Update retry attempt 1 successful" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:02Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=28094005 workflow=test-cron-wf-28skf
time="2020-04-21T11:34:03Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:06Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-mz7vf
time="2020-04-21T11:34:06Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-28skf
time="2020-04-21T11:34:06Z" level=info msg="Processing workflow" namespace=default workflow=test-cron-wf-dn6j8

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vilmosnagy** [comment]
I see that the #2694 is similar, but as far as I understand we have only one `workflow-controller`, so that's not the problem :\

**Comment by alexec** [comment]
I think we should fix in v2.8? By creating deterministic workflow names?

**Comment by simster7** [comment]
This issue should be unrelated to naming

**Comment by vilmosnagy** [comment]
It works well if I start an argo in a k3d cluster on my local machine - so my guess would be it has nothing to do with the naming.

The versions in the k3d cluster:

```
[vilmosnagy@vnagy-dell ~]$ argo version
argo: v2.6.1
  BuildDate: 2020-03-04T21:25:34Z
  GitCommit: 842739d7831cc5b417c4f524ed85288408a32bbf
  GitTreeState: clean
  GitTag: v2.6.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
[vilmosnagy@vnagy-dell ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by simster7** [comment]
@vilmosnagy Could I ask some more details about this?

* Does it happen reliably or is it a one off?
* Does it happen with other schedules or just with `* * * * *`?
* Does this happen in `2.7.5`?
* Does this happen in any other cluster types?

Don't worry if you can't answer every question, but the more the better in tracking this down.

**Comment by vilmosnagy** [comment]
> Does it happen reliably or is it a one off?
It happens every time on that cluster.

> Does it happen with other schedules or just with `* * * * *`?
It happens with the following schedule as well: `5 * * * *`  As far as I remember, I tried it with multiple schedules (every second hour, once a day at a given time, etc), and it happened every time.

> Does this happen in 2.7.5?
I'll talk with the guys, who administer that cluster, wether we can upgrade it or not.

> Does this happen in 2.7.5?
I'm not sure that I understand the question, but I'll talk with the devops guys about this  as well. :slightly_smiling_face:

**Comment by alexec** [comment]
Two controllers?

**Comment by vilmosnagy** [comment]
This command should list the controllers, isn't it: `kubectl get pods -l app=argo-workflow-controller -n argo-system -o name`

Then we have only one controller:

```
[vilmosnagy@vnagy-dell ~]$ kubectl get pods -l app=argo-workflow-controller -n argo-system -o name
pod/argo-workflow-controller-6587d86698-qs45f
```

**Comment by vilmosnagy** [comment]
This command should list the controllers, isn't it: `kubectl get pods -l app=argo-workflow-controller -n argo-system`

Then we have only one controller:

```
[vilmosnagy@vnagy-dell ~]$ kubectl get pods -l app=argo-workflow-controller -n argo-system 
NAME                                        READY   STATUS    RESTARTS   AGE
argo-workflow-controller-6587d86698-qs45f   1/1     Running   5          15d
[vilmosnagy@vnagy-dell ~]$ 

```

**Comment by stefansedich** [comment]
We are seeing the same running one controller too.

**Comment by simster7** [comment]
Will look into this this week

**Comment by simster7** [comment]
This could potentially be fixed by: https://github.com/argoproj/argo/pull/2851

**Comment by simster7** [comment]
@vilmosnagy I spent some good time looking over the logs you posted, thinking it could be a possible race condition started when Workflows finish too close to the scheduled time. However, I have a big doubt to this theory:

If the same controlling was scheduling the Workflow multiple times then we would see this line in the logs more than once every minute:

```
time="2020-04-21T11:34:00Z" level=info msg="Running test-cron-wf"
```

Any time a Workflow from a CronWorkflow is submitted, that log is sent out:

https://github.com/argoproj/argo/blob/a0035dd58609d744a6fa304e51d61474f25c817d/workflow/cron/operator.go#L44

So we should see it once per every Workflow scheduled from the WorkflowController.

In fact, we see it appears _less_ than expected during normal operation. We should be seeing it once per minute in the logs you posted, but it only appears once across two minutes.

I know you've already discarded this, but this leads me to believe that **this issue is caused by two competing controllers that are wrangling over the same `CronWorkflow` object.**

**Most importantly, I found the following error in your logs multiple times:**

```
the object has been modified; please apply your changes to the latest version and try again Conflict
```

Which is pretty much a guarantee that there are multiple controllers fighting over the same resource. This error says that some other entity changed the CRD from the time it was picked up by the controller to the time it tried to persist it again.

Can you make super sure there aren't multiple controllers in your cluster?

Can you run the command you posted with the `--all-namespaces` flag?
```
$ kubectl get pods -l app=argo-workflow-controller  --all-namespaces
```

Also, when we install locally the label is `app=workflow-controller` instead of `app=argo-workflow-controller`. Can you try this too?
```
$ kubectl get pods -l app=workflow-controller  --all-namespaces
```

**Comment by vilmosnagy** [comment]
@simster7 thanks for the time you spent with my issue. I've spoke with our devops guy, and after all there's an other controller in an other namespace.

I'm still not able to see it (even with the `--all-namespaces` flag), but we sorted it out after all.

Thanks again.

**Comment by rosscdh** [comment]
+1 here same issue

argo 2.8.1 cronworkflow dupes

**Comment by simster7** [comment]
@rosscdh Please make sure that you only have one Argo controller instance running at the same time.

**Comment by rosscdh** [comment]
yep read the ticket .. only 1 controller

**Comment by rosscdh** [comment]
still the same issue.. cron gets created 2x

**Comment by simster7** [comment]
Can you post the `workflow-controller` logs?

**Comment by robertmujica** [comment]
@simster7 hey we are getting this error, but as you can see below we do have two workflow-controllers, one for Argo and one for Kubeflow ( as you may know kubeflow depends / run on top of Argo ), but they are on separate namespaces, my question is: is there a workaround to ensure it only runs once ? we did try concurrencyPolicy: "Forbid" but didn't work.

NAMESPACE   NAME                                   READY   STATUS    RESTARTS   AGE
argo        workflow-controller-77d4cfd5f5-7sms9   1/1     Running   0          7d
kubeflow    workflow-controller-7c59f775f4-2lvg9   1/1     Running   0          6d15h

this is our argo version:

argo: v2.10.0-rc6+cb3536f.dirty
  BuildDate: 2020-08-06T22:47:03Z
  GitCommit: cb3536f9d1dd64258c1c3d737bb115bdab923e58
  GitTreeState: dirty
  GitTag: v2.10.0-rc6
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64

**Comment by simster7** [comment]
@robertmujica You need to set up `instanceId`. Please see https://github.com/argoproj/argo/issues/4036

**Comment by robertmujica** [comment]
Thanks @simster7 , i partially fixed the problem usinginstanceid, however after i removed all cron workflows i still see workflow being scheduled, like some sort of daemon running, it also stops when i delete the workflow-controller deployment, is there a way i purge / flush these workflows ?

**Comment by robertmujica** [comment]
Quick update, u deleted all workflow-controllers ( including kubeflow ) and redeploy ConfigMap with instanceid and now CronWorkflows are running once as per cron expressoin. Thanks @simster7 for clue above, definetly that is the  fix when kubeflow and argo lives on same cluster no matter if they are on different namespace
