### ISSUE TITLE
Issue passing List of Objects from workflow parameters

### ISSUE THREAD

**Issue by TTRh** [argoproj/argo#3170]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Using `withParam` with a list of complex parameter, it fails if there is a list inside the item.

**What you expected to happen**:

List type should be supported ?
Based on https://github.com/argoproj/argo/issues/2660
I was expecting version 2.8.1 fix this but seems not the case.

**How to reproduce it (as minimally and precisely as possible)**:

Derivated from the doc : 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-arg-
spec:
  entrypoint: loop-param-arg-example
  arguments:
    parameters:
    - name: os-list                                     # a list of items
      value: |
        [
          { "image": "debian", "tag": "9.1", "parameters": ["foo", "bar"]},
          { "image": "alpine", "tag": "3.6" , "parameters": "bar"}
        ]

  templates:
  - name: loop-param-arg-example
    inputs:
      parameters:
      - name: os-list
    steps:
    - - name: test-linux
        template: cat-os-release
        arguments:
          parameters:
          - name: image
            value: "{{item.image}}"
          - name: tag
            value: "{{item.tag}}"
          - name: item
            value: "{{item}}"
        withParam: "{{inputs.parameters.os-list}}"      # parameter specifies the list to iterate over

  # This template is the same as in the previous example
  - name: cat-os-release
    inputs:
      parameters:
      - name: image
      - name: tag
      - name: item
    container:
      image: "{{inputs.parameters.image}}:{{inputs.parameters.tag}}"
      command: [echo]
      args: ["{{inputs.parameters.item}}"]
```

**Environment**:

- Argo version:
```
▶ argo version
argo: v2.8.1
  BuildDate: 2020-05-28T23:39:46Z
  GitCommit: 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8
  GitTreeState: clean
  GitTag: v2.8.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-07-18T09:18:22Z"
  compiler: gc
  gitCommit: 4485c6f18cee9a5d3c3b4e523bd27972b1b53892
  gitTreeState: clean
  gitVersion: v1.15.1
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-03-18T04:24:17Z"
  compiler: gc
  gitCommit: f459c0672169dd35e77af56c24556530a05e9ab1
  gitTreeState: clean
  gitVersion: v1.14.9-eks-f459c0
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow result:

```
argo --loglevel DEBUG get <workflowname>

DEBU[0000] CLI version                                   version="{v2.8.1 2020-05-28T23:39:46Z 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8 v2.8.1 clean go1.13.4 gc linux/amd64}"
DEBU[0000] Client options                                opts="{{ false false} 0x1574ab0 0xc0000f39f0}"
Name:                loops-param-arg-gpklw
Namespace:           unicron-serenity-pro
ServiceAccount:      default
Status:              Failed
Message:             json: error calling MarshalJSON for type v1alpha1.ItemValue: impossible ItemValue.Type
Created:             Thu Jun 04 14:49:25 +0200 (4 minutes ago)
Started:             Thu Jun 04 14:49:25 +0200 (4 minutes ago)
Finished:            Thu Jun 04 14:49:26 +0200 (4 minutes ago)
Duration:            1 second
Parameters:          
  os-list:           [
  { "image": "debian", "tag": "9.1", "parameters": ["foo", "bar"]},
  { "image": "alpine", "tag": "3.6" , "parameters": "bar"}
]


STEP                      TEMPLATE                PODNAME  DURATION  MESSAGE
 ✖ loops-param-arg-gpklw  loop-param-arg-example                     json: error calling MarshalJSON for type v1alpha1.ItemValue: impossible ItemValue.Type
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
The issue fixed in v2.8.1.  try on  v2.8.1

**Comment by TTRh** [comment]
> The issue fixed in v2.8.1. Try on v2.8.1

i'm using version 2.8.1 as in the shown in the logs  : 

```
DEBU[0000] CLI version                                   version="{v2.8.1 2020-05-28T23:39:46Z 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8 v2.8.1 clean go1.13.4 gc linux/amd64}"
```
is the example works for you ?

**Comment by TTRh** [comment]
@sarabala1979 do i miss something or issue is still valid ?  Is the workflow snippet works for you ?
