### ISSUE TITLE
UI "Failed to load logs: Unsuccessful HTTP response"

### ISSUE THREAD

**Issue by muwon** [argoproj/argo#4368]
## Summary 

Submit sample hello-world workflow using command line "argo submit" or via UI.  The workflow completed successfully. But when click on [LOGS], it shows "Failed to load logs: Unsuccessful HTTP response".

## Diagnostics

What Kubernetes provider are you using? 
v1.16.9
What version of Argo Workflows are you running? 
v2.11.3 and v2.11.6
```yaml
apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    creationTimestamp: "2020-10-24T18:11:29Z"
    generateName: hello-world-
    generation: 6
    labels:
      workflows.argoproj.io/archive-strategy: "false"
      workflows.argoproj.io/completed: "true"
      workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
      workflows.argoproj.io/phase: Succeeded
    name: hello-world-s62zf
    namespace: argo
    resourceVersion: "590176909"
    selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/hello-world-s62zf
    uid: 64f4b05c-a3bc-4d34-bc99-e82125dcc4fa
  spec:
    arguments: {}
    entrypoint: whalesay
    templates:
    - arguments: {}
      container:
        args:
        - hello world
        command:
        - cowsay
        image: docker/whalesay:latest
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: whalesay
      outputs: {}
    ttlStrategy:
      secondsAfterCompletion: 84600
      secondsAfterFailure: 600
      secondsAfterSuccess: 600
  status:
    conditions:
    - status: "True"
      type: Completed
    finishedAt: "2020-10-24T18:11:36Z"
    nodes:
      hello-world-s62zf:
        displayName: hello-world-s62zf
        finishedAt: "2020-10-24T18:11:34Z"
        hostNodeName: cn-hangzhou.10.66.189.97
        id: hello-world-s62zf
        name: hello-world-s62zf
        outputs:
          exitCode: "0"
        phase: Succeeded
        resourcesDuration:
          cpu: 4
          memory: 4
        startedAt: "2020-10-24T18:11:29Z"
        templateName: whalesay
        templateScope: local/hello-world-s62zf
        type: Pod
    phase: Succeeded
    resourcesDuration:
      cpu: 4
      memory: 4
    startedAt: "2020-10-24T18:11:29Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: "" 
```

```
time="2020-10-24T18:11:29Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"hello-world-s62zf\", UID:\"64f4b05c-a3bc-4d34-bc99-e82125dcc4fa\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"590176574\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowRunning' Workflow Running"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:29Z" level=debug msg="Initializing node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=info msg="Pod node hello-world-s62zf initialized Pending" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=debug msg="Executing node hello-world-s62zf with container template: &Template{Name:whalesay,Template:,Arguments:Arguments{Parameters:[]Parameter{},Artifacts:[]Artifact{},},TemplateRef:nil,Inputs:Inputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},},Outputs:Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},Result:nil,ExitCode:nil,},NodeSelector:map[string]string{},Affinity:nil,Metadata:Metadata{Annotations:map[string]string{},Labels:map[string]string{},},Daemon:nil,Steps:[]ParallelSteps{},Container:&v1.Container{Name:,Image:docker/whalesay:latest,Command:[cowsay],Args:[hello world],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,},Script:nil,Resource:nil,DAG:nil,Suspend:nil,Volumes:[]Volume{},InitContainers:[]UserContainer{},Sidecars:[]UserContainer{},ArchiveLocation:nil,ActiveDeadlineSeconds:<nil>,RetryStrategy:nil,Parallelism:nil,Tolerations:[]Toleration{},SchedulerName:,PriorityClassName:,Priority:nil,ServiceAccountName:,HostAliases:[]HostAlias{},SecurityContext:nil,PodSpecPatch:,AutomountServiceAccountToken:nil,Executor:nil,ResubmitPendingPods:false,Metrics:nil,Synchronization:nil,Memoize:nil,Timeout:,}\n" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=debug msg="Creating Pod: hello-world-s62zf (hello-world-s62zf)" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=debug msg="archive location unnecessary" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=info msg="Created pod: hello-world-s62zf (hello-world-s62zf)" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:29Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=590176577 workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=info msg="Updating node hello-world-s62zf message: ContainerCreating"
time="2020-10-24T18:11:30Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:30Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:30Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:30Z" level=debug msg="Executing node hello-world-s62zf of Pod is Pending" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=debug msg="Executing node hello-world-s62zf with container template: &Template{Name:whalesay,Template:,Arguments:Arguments{Parameters:[]Parameter{},Artifacts:[]Artifact{},},TemplateRef:nil,Inputs:Inputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},},Outputs:Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},Result:nil,ExitCode:nil,},NodeSelector:map[string]string{},Affinity:nil,Metadata:Metadata{Annotations:map[string]string{},Labels:map[string]string{},},Daemon:nil,Steps:[]ParallelSteps{},Container:&v1.Container{Name:,Image:docker/whalesay:latest,Command:[cowsay],Args:[hello world],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,},Script:nil,Resource:nil,DAG:nil,Suspend:nil,Volumes:[]Volume{},InitContainers:[]UserContainer{},Sidecars:[]UserContainer{},ArchiveLocation:nil,ActiveDeadlineSeconds:<nil>,RetryStrategy:nil,Parallelism:nil,Tolerations:[]Toleration{},SchedulerName:,PriorityClassName:,Priority:nil,ServiceAccountName:,HostAliases:[]HostAlias{},SecurityContext:nil,PodSpecPatch:,AutomountServiceAccountToken:nil,Executor:nil,ResubmitPendingPods:false,Metrics:nil,Synchronization:nil,Memoize:nil,Timeout:,}\n" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=debug msg="Creating Pod: hello-world-s62zf (hello-world-s62zf)" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=debug msg="archive location unnecessary" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=info msg="Skipped pod hello-world-s62zf (hello-world-s62zf) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-s62zf
time="2020-10-24T18:11:30Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=590176615 workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:31Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:31Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:31Z" level=debug msg="Executing node hello-world-s62zf of Pod is Pending" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=debug msg="Executing node hello-world-s62zf with container template: &Template{Name:whalesay,Template:,Arguments:Arguments{Parameters:[]Parameter{},Artifacts:[]Artifact{},},TemplateRef:nil,Inputs:Inputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},},Outputs:Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},Result:nil,ExitCode:nil,},NodeSelector:map[string]string{},Affinity:nil,Metadata:Metadata{Annotations:map[string]string{},Labels:map[string]string{},},Daemon:nil,Steps:[]ParallelSteps{},Container:&v1.Container{Name:,Image:docker/whalesay:latest,Command:[cowsay],Args:[hello world],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,},Script:nil,Resource:nil,DAG:nil,Suspend:nil,Volumes:[]Volume{},InitContainers:[]UserContainer{},Sidecars:[]UserContainer{},ArchiveLocation:nil,ActiveDeadlineSeconds:<nil>,RetryStrategy:nil,Parallelism:nil,Tolerations:[]Toleration{},SchedulerName:,PriorityClassName:,Priority:nil,ServiceAccountName:,HostAliases:[]HostAlias{},SecurityContext:nil,PodSpecPatch:,AutomountServiceAccountToken:nil,Executor:nil,ResubmitPendingPods:false,Metrics:nil,Synchronization:nil,Memoize:nil,Timeout:,}\n" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=debug msg="Creating Pod: hello-world-s62zf (hello-world-s62zf)" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=debug msg="archive location unnecessary" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:31Z" level=info msg="Skipped pod hello-world-s62zf (hello-world-s62zf) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-s62zf
time="2020-10-24T18:11:34Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:34Z" level=info msg="Updating node hello-world-s62zf status Pending -> Running"
time="2020-10-24T18:11:34Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:34Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:34Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:34Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:34Z" level=debug msg="Executing node hello-world-s62zf of Pod is Running" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:34Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=590176803 workflow=hello-world-s62zf
time="2020-10-24T18:11:35Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:35Z" level=info msg="Setting node hello-world-s62zf outputs"
time="2020-10-24T18:11:35Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:35Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:35Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:35Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:35Z" level=debug msg="Executing node hello-world-s62zf of Pod is Running" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:35Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=590176846 workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Updating node hello-world-s62zf status Running -> Succeeded"
time="2020-10-24T18:11:36Z" level=debug msg="Evaluating node hello-world-s62zf: template: *v1alpha1.WorkflowStep (whalesay), boundaryID: " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:36Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:36Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=hello-world-s62zf)" depth=0 tmpl="*v1alpha1.WorkflowStep (whalesay)"
time="2020-10-24T18:11:36Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"hello-world-s62zf\", UID:\"64f4b05c-a3bc-4d34-bc99-e82125dcc4fa\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"590176846\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeSucceeded' Succeeded node hello-world-s62zf"
time="2020-10-24T18:11:36Z" level=debug msg="Node hello-world-s62zf already completed" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"argo\", Name:\"hello-world-s62zf\", UID:\"64f4b05c-a3bc-4d34-bc99-e82125dcc4fa\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"590176846\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowSucceeded' Workflow completed"
time="2020-10-24T18:11:36Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=590176909 workflow=hello-world-s62zf
time="2020-10-24T18:11:36Z" level=info msg="Found Workflow argo/hello-world-s62zf set expire at 2020-10-24 18:21:36 +0000 UTC (9m59.163638688s from now)"
time="2020-10-24T18:11:36Z" level=info msg="Queueing workflow argo/hello-world-s62zf for delete in 9m59.163638688s"
time="2020-10-24T18:11:36Z" level=info msg="Found Workflow argo/hello-world-s62zf set expire at 2020-10-24 18:21:36 +0000 UTC (9m59.163613306s from now)"
time="2020-10-24T18:11:36Z" level=info msg="Queueing workflow argo/hello-world-s62zf for delete in 9m59.163613306s"
time="2020-10-24T18:11:37Z" level=info msg="Labeled pod completed" namespace=argo pod=hello-world-s62zf
time="2020-10-24T18:21:36Z" level=info msg="Deleting TTL expired workflow argo/hello-world-s62zf"
time="2020-10-24T18:21:36Z" level=info msg="Successfully deleted 'argo/hello-world-s62zf'"
time="2020-10-24T18:21:36Z" level=info msg="Found Workflow argo/hello-world-s62zf set expire at 2020-10-24 18:21:36 +0000 UTC (-9.038981ms from now)"
time="2020-10-24T18:21:36Z" level=info msg="Queueing workflow argo/hello-world-s62zf for delete in 0s"
time="2020-10-24T18:21:36Z" level=info msg="Found Workflow argo/hello-world-s62zf set expire at 2020-10-24 18:21:36 +0000 UTC (-9.038979ms from now)"
time="2020-10-24T18:21:36Z" level=info msg="Queueing workflow argo/hello-world-s62zf for delete in 0s"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by saiyidi** [comment]
![errorArgologs](https://user-images.githubusercontent.com/52663864/97156840-90a1c500-1777-11eb-89c3-947b5a3faefb.jpg)
I too get this

**Comment by alexec** [comment]
Could you please check in your web console to see what the exact error is?

**Comment by muwon** [comment]
Error code is 500.  Please see attached screenshot.
<img width="1239" alt="Screen Shot 2020-10-26 at 6 49 43 PM" src="https://user-images.githubusercontent.com/7505277/97247174-5ad2ff80-17bc-11eb-9e09-589b3942ddb6.png">

**Comment by alexec** [comment]
Thank you. I can now see that you have a 404 and 500 error. I'd like to request the argo-server logs for those requests so we can see the underlying error.

**Comment by muwon** [comment]
@alexec  The problem actually happens in two places with the same error messages but different status codes.

In the "Ttimeline" page, the Hello-World workflow is completed and succeeded.  Clicking on the [LOGS] button, the status codes are 200 and 500.  UI is able to find the logs:
![Screen Shot 2020-10-27 at 11 00 21 AM](https://user-images.githubusercontent.com/7505277/97343404-b052ef00-1844-11eb-93aa-23a9b296d1cc.png)

Here are the argo-server logs for that one:
`time="2020-10-27T17:59:09Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-10-27T17:59:09Z" grpc.time_ms=27.228 span.kind=server system=grpc
time="2020-10-27T17:59:09Z" level=info msg="Download artifact" artifactName=main-logs namespace=argo nodeId=hello-world-qbcrt workflowName=hello-world-qbcrt
time="2020-10-27T17:59:09Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-10-27T17:59:09Z" grpc.time_ms=22.513 span.kind=server system=grpc
time="2020-10-27T17:59:09Z" level=info msg="Download artifact" artifactName=main-logs namespace=argo nodeId=hello-world-qbcrt workflowName=hello-world-qbcrt
time="2020-10-27T17:59:28Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-10-27T17:58:28Z" grpc.time_ms=60000.223 span.kind=server system=grpc
`

The other place is what I reported earlier.  That is, clicking on [LOGS] of a completed & succeeded Hello-World workflow in the “Archived Workflows” list.  The status codes are 404 and 500.  The argo-server logs as follow:
`time="2020-10-27T17:50:27Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"hello-world-xh48v\" not found" grpc.code=NotFound grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-10-27T17:50:27Z" grpc.time_ms=4.053 span.kind=server system=grpc
time="2020-10-27T17:50:27Z" level=info msg="Download artifact" artifactName=main-logs nodeId=hello-world-xh48v uid=cc494cb7-e06e-45c0-b1af-b45c21b02e5a
`

**Comment by alexec** [comment]
I'm confused by this bug. What are you trying to do that you cannot? You said you're looking at workflow logs, but the screenshots show archived workflows? Then there is a screenshot showing the logs?

**Comment by muwon** [comment]
I'd expect to see the workflow logs in both places, "Timeline" page and "Archived Workflows" page without the "Failed to load logs: Unsuccessful HTTP response" error message.

If I just launch one of those random workflow samples from the UI using the "SUBMIT NEW WORKFLOW" button, e.g. awesome-whale, clicking on the LOGS button also shows the same error message.

**Comment by alexec** [comment]
The error seems to occur (in one instance) because the workflow is not found.  I think the error would be better be a 404 than a 500 error.

**Comment by muwon** [comment]
As I pointed out earlier:
- Timeline page:  Status codes are 200 and 500
- Archived Workflows page: Status codes are 404 and 500

**Comment by hikoz** [comment]
It looks argo-ui tried to fetch log twice. from pod and archivedLog.

**Comment by alexec** [comment]
Ok. I think this bug is fixed in latest. Can you please try `argoproj/argocli:latest`?

**Comment by muwon** [comment]
It is not fixed entirely.  Status 404 is still there.  With hello-world WF, it took somewhere like a couple of seconds in "Waiting for data..." then it showed the log successfully without the error message.  But with a random sample launched from the UI, it just stuck in "Waiting for data...", and turned into a bunch of 404's
![Screen Shot 2020-10-28 at 11 39 50 AM](https://user-images.githubusercontent.com/7505277/97482967-18bcd180-1914-11eb-81f2-389f8893f278.png)
![Screen Shot 2020-10-28 at 11 46 54 AM](https://user-images.githubusercontent.com/7505277/97482985-1ce8ef00-1914-11eb-9311-7ff8d6b02edf.png)

Logs:
`time="2020-10-28T18:53:46Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"fantastic-whale10\" not found" grpc.code=NotFound grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-10-28T18:53:46Z" grpc.time_ms=5.49 span.kind=server system=grpc
time="2020-10-28T18:53:46Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"fantastic-whale10\" not found" grpc.code=NotFound grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-10-28T18:53:46Z" grpc.time_ms=5.63 span.kind=server system=grpc
time="2020-10-28T18:53:46Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"fantastic-whale10\" not found" grpc.code=NotFound grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-10-28T18:53:46Z" grpc.time_ms=5.839 span.kind=server system=grpc
time="2020-10-28T18:53:46Z" level=info msg="finished streaming call with code NotFound" error="rpc error: code = NotFound desc = workflows.argoproj.io \"fantastic-whale10\" not found" grpc.code=NotFound grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-10-28T18:53:46Z" grpc.time_ms=10.995 span.kind=server system=grpc`

**Comment by alexec** [comment]
In the examples when you are waiting for data, can the logs be retrieved from the artifacts?
